ucm2: Add support for SC7180 Trogdor Lazor Chromebooks
alsa-project/alsa-ucm-conf pull request #118
Opened 2021-11-10 13:22 UTC by kholk

Almost all Trogdor Chromebooks are using RT5682 for headphones/headset
on 3.5mm jack, internal microphone and headset microphone, and MAX98357A
for the internal speakers (Lazor and Limozeen).

This adds support for the sc7180-rt5682-max98357a-1mic sound card found
on the aforementioned Chromebooks.

Signed-off-by: AngeloGioacchino Del Regno <angelogioacchino.delregno@collabora.com>

Tested on sc7180-trogdor-lazor-limozeen-nots.

2021-11-16 13:44 UTC, perexg requested changes

2021-11-16 13:44 UTC, perexg commented on ucm2/Qualcomm/sc7180/rt5682-max98357a/HiFi.conf
> +		cset "name='IF1 01 ADC Swap Mux' 1"
It seems that Mic and Headphones mic conflicts ? Add ConflictingDevice section to one device (the alsa-lib will add it for the other automatically).

2021-11-16 13:44 UTC, perexg commented on ucm2/Qualcomm/sc7180/rt5682-max98357a/sc7180-rt5682-max98357a-1mic.conf
> +SectionUseCase."HDMI" {
Move HDMI device to HiFi.conf.

2021-12-01 14:32 UTC, kholk commented
PR updated.

2021-12-09 09:56 UTC, perexg commented
Thanks. Merged now in cefbdeb9f763ab4cbba1c338716d40acb6a4e43a .

2021-12-09 09:56 UTC, closed without merging