ucm2: add profile for the Librem 5
alsa-project/alsa-ucm-conf pull request #181
Opened 2022-06-29 22:26 UTC by craftyguy

cc @agx

2022-06-30 06:58 UTC, agx commented
@craftyguy thanks for taking a look at this! Would be great to have it upstream. There's  rework pending here https://source.puri.sm/Librem5/librem5-base/-/merge_requests/311 which might make sense to have upstream right away. What do you think?

2022-06-30 15:57 UTC, craftyguy commented
> There's rework pending here https://source.puri.sm/Librem5/librem5-base/-/merge_requests/311 which might make sense to have upstream right away. What do you think?

@agx I saw that, and based on the comments it still seemed WIP with the last update a couple of months ago... So I thought it would be better to upstream a known working config, then it could be tweaked later to perfection.

But obviously if it's in much better shape than what I think from reading the discussion, I'd have no problem updating this patch. My main motivation is to just get *something* upstream to hopefully help with audio on this platform breaking every time alsa is updated.

2022-07-29 10:55 UTC, agx commented
Given that reworking the profile seems to have stalled I think this would be good to have as a starting point!

2022-08-02 13:44 UTC, agx commented
and just in case:

```
Tested-by: Guido Günther <agx@sigxcpu.org>
```

2022-10-03 08:25 UTC, perexg requested changes
Please, resolve my objections for all devices (MixerElem, 2 channels, shorter PCM devices).

2022-10-03 08:25 UTC, perexg commented on ucm2/NXP/iMX8/Librem_5/HiFi.conf
> +		cset "name='Digital Playback Volume' 100,100"
This settings belongs to the BootSection.

2022-10-03 08:25 UTC, perexg commented on ucm2/NXP/iMX8/Librem_5/HiFi.conf
> +		cset "name='Digital Playback Volume' 0,0"
The volumes should not be touched in enable/disable sequences. Keep the user settings.

2022-10-03 08:25 UTC, perexg commented on ucm2/NXP/iMX8/Librem_5/HiFi.conf
> +	Value {
Remove empty blocks.

2022-10-03 08:25 UTC, perexg commented on ucm2/NXP/iMX8/Librem_5/HiFi.conf
> +		cset "name='Speaker Volume' 121,121"
Do not set volume in enable/disable sequences.

2022-10-03 08:25 UTC, perexg commented on ucm2/NXP/iMX8/Librem_5/HiFi.conf
> +		PlaybackSwitch "name='Speaker Switch'"
Missing 'PlaybackMixerElem "Speaker"` value for PA/PW to enable hardware volume control.

2022-10-03 08:25 UTC, perexg commented on ucm2/NXP/iMX8/Librem_5/HiFi.conf
> +		PlaybackChannels "2"
2 channels are the default. Remove this line.

2022-10-03 08:25 UTC, perexg commented on ucm2/NXP/iMX8/Librem_5/HiFi.conf
> +		CapturePCM "hw:${CardId},0"
First (zero) PCM device is the default. Use the shorter `CapturePCM "hw:${CardId}"`

2022-10-08 07:57 UTC, perexg approved these changes
The verb should also call DisableSequence for all devices when enabled like: 

https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/HDA/HiFi.conf#L3-L9

2022-10-08 07:57 UTC, perexg commented on ucm2/NXP/iMX8/Librem_5/HiFi.conf
> +                PlaybackMixerElem "Handset"
It should be "Speaker" (see `amixer scontrols`).

2022-10-08 07:57 UTC, perexg commented on ucm2/NXP/iMX8/Librem_5/HiFi.conf
> +		CaptureVolume "name='Digital Capture Volume'"
Missing `CaptureMixerElem "Digital"` here.

2022-10-08 07:57 UTC, perexg commented on ucm2/NXP/iMX8/Librem_5/HiFi.conf
> +		CaptureVolume "name='Capture Volume'"
Missing `CaptureMixerElem "Capture"` here.

2022-10-08 07:57 UTC, perexg commented on ucm2/NXP/iMX8/Librem_5/HiFi.conf
> +		CaptureChannels "2"
Remove CaptureChannels 2 (the default).

2022-11-16 14:58 UTC, closed without merging