Add correct support for Rane SL-1
alsa-project/alsa-ucm-conf pull request #187
Opened 2022-07-10 16:28 UTC by christophehenry

Following [this ticket](https://bugzilla.kernel.org/show_bug.cgi?id=216082) on kernel bugzilla, I'm trying to add corect support for [Rane SL-1](https://cdn.korn.eu/pictures/product/400/040506_3.jpg), an old USB soundcard featuring 2 stereo inputs (RCA) and 3 stereo outputs (2 RCA, 1 6.3mm jack).

Currently, `alsa-info.sh` does show the correct number of inputs and outputs But neither `pavucontrol` nor Mixxx do. I was told complex hardware should be described via UCM but the syntax is unfortunately very poorly documented so I can get my head around it and get `pavucontrol` to show all the inputs and outputs.

Here's what I have so far which, to my disappointment, does not work. If I put only 1 `SectionDevice` section in the file, I can display 1 ouput under `pavucontrol`. With 2 `SectionDevice`, nothing shows.

Without any UCM file, `pavucontrol` shows 2 outputs, 1 intputs (instead of 3) and Mixxx shows 2 outputs and not input.

2022-07-10 17:48 UTC, perexg commented
Please, use https://github.com/alsa-project/alsa-ucm-conf/blob/master/ucm2/USB-Audio/Dell/WD15-Dock-HiFi.conf (without If blocks - use straight values) as a template as suggested in the kernel bugzilla. Your hardware does not require to split multichannel PCM streams. Just define correct `PlaybackPCM` and `CapturePCM` devices.

2022-07-27 15:58 UTC, christophehenry commented
I managed to get the 6.3mm Jack input detected, but I'm still puzzled by those 2 stereo I can't detect anywhere. Do you have a support channel (IRC or Matrix) anywhere where I can reach out to get live help? [The wiki still indicates Freenode](https://www.alsa-project.org/wiki/Irc).

2022-07-28 10:31 UTC, christophehenry commented on ucm2/USB-Audio/Rane/SL-1-HiFi.conf
> +		CapturePCM "hw:${CardId},4"
Unfortunately, that doesn't work either, I tested it, too (I should have posted the all the results):

```
# arecord --device=hw:2,0 -f S16_LE  -r44100 -s1
arecord: main:867: audio open error: No such file or directory
# arecord --device=hw:2,1 -f S16_LE  -r44100 -s1
arecord: main:867: audio open error: No such file or directory
```

Modifying the configuration doesn't change anything.

```
SectionDevice."Line1" {
	Comment "Line out 1"

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"

		PlaybackChannels 2
		PlaybackMixerElem "Line out 1"
		PlaybackVolume "Line out 1 Playback Volume"
		PlaybackSwitch "Line out 1 Playback Switch"
	}
}

SectionDevice."Line2" {
	Comment "Line out 2"

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},1"

		PlaybackChannels 2
		PlaybackMixerElem "Line out 2"
		PlaybackVolume "Line out 2 Playback Volume"
		PlaybackSwitch "Line out 2 Playback Switch"
	}
}

SectionDevice."Mic3" {
	Comment "Mic"

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},2"

		CaptureChannels 1
		CaptureMixerElem "Mic"
		CaptureVolume "Mic Playback Volume"
		CaptureSwitch "Mic Playback Switch"
	}
}
```

produces:

![](https://user-images.githubusercontent.com/22097904/181484400-e33b9136-e2ae-4fc3-abda-ffe24ba0e4a0.png)

The 2 stereo RCA inputs are missing, which is expected, but the rest is here. 

But

```
SectionDevice."Line1" {
	Comment "Line out 1"

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"

		PlaybackChannels 2
		PlaybackMixerElem "Line out 1"
		PlaybackVolume "Line out 1 Playback Volume"
		PlaybackSwitch "Line out 1 Playback Switch"
	}
}

SectionDevice."Line2" {
	Comment "Line out 2"

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},1"

		PlaybackChannels 2
		PlaybackMixerElem "Line out 2"
		PlaybackVolume "Line out 2 Playback Volume"
		PlaybackSwitch "Line out 2 Playback Switch"
	}
}

SectionDevice."Mic1" {
	Comment "Input 1"

	Value {
		CapturePriority 300
		CapturePCM "hw:${CardId},0"

		CaptureChannels 2
		CaptureMixerElem "Input 1"
		CaptureVolume "Input 1 Playback Volume"
		CaptureSwitch "Input 1 Playback Switch"
	}
}

SectionDevice."Mic2" {
	Comment "Input 2"

	Value {
		CapturePriority 200
		CapturePCM "hw:${CardId},1"

		CaptureChannels 2
		CaptureMixerElem "Input 2"
		CaptureVolume "Input 2 Playback Volume"
		CaptureSwitch "Input 2 Playback Switch"
	}
}

SectionDevice."Mic3" {
	Comment "Mic"

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId},2"

		CaptureChannels 1
		CaptureMixerElem "Mic"
		CaptureVolume "Mic Playback Volume"
		CaptureSwitch "Mic Playback Switch"
	}
}
```

produces:

![](https://user-images.githubusercontent.com/22097904/181484488-362afdfa-890f-45bb-a2cc-ecaab463a4b1.png)

Everything regarding the SL-1 has disappeared.

I can guarantee that the problem does not come from the hardware. I tested it on Windows using Serato Scratch Live and it was working as expected.

2022-07-28 10:32 UTC, perexg commented on ucm2/USB-Audio/Rane/SL-1-HiFi.conf
> +		PlaybackMixerElem "Line out 1"
This USB card does not have any controls (exported from the driver), so `PlaybackMixerElem` and `PlaybackVolume` / `PlaybackSwitch` lines should be removed.

2022-07-28 10:35 UTC, perexg commented on ucm2/USB-Audio/Rane/SL-1-HiFi.conf
> +		CapturePCM "hw:${CardId},4"
> Unfortunately, that doesn't work either, I tested it, too (I should have posted the all the results):
> 
> ```
> # arecord --device=hw:2,0 -f S16_LE  -r44100 -s1
> arecord: main:867: audio open error: No such file or directory
> # arecord --device=hw:2,1 -f S16_LE  -r44100 -s1
> arecord: main:867: audio open error: No such file or directory

Those commands should work. Do you see any errors in `dmesg` ?

2022-07-28 10:41 UTC, christophehenry commented on ucm2/USB-Audio/Rane/SL-1-HiFi.conf
> +		CapturePCM "hw:${CardId},4"
No message at all in `dmesg` when executing these commands. No error when plugin the USB card:

```
[ 8827.649083] usb 1-1: new full-speed USB device number 6 using xhci_hcd
[ 8827.967295] usb 1-1: New USB device found, idVendor=13e5, idProduct=0001, bcdDevice= 1.00
[ 8827.967301] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 8827.967304] usb 1-1: Product: Serato Scratch LIVE(c)2004
[ 8827.967306] usb 1-1: Manufacturer: Serato
[ 8828.026191] usb 1-1: Found post-registration device assignment: 13e50001:02
[ 8828.071190] usb 1-1: Found post-registration device assignment: 13e50001:05
```

2022-07-28 10:48 UTC, perexg commented on ucm2/USB-Audio/Rane/SL-1-HiFi.conf
> +		CapturePCM "hw:${CardId},4"
> Di you know what is this `Found post-registration device assignment: 13e50001:05` line about?

https://patchwork.kernel.org/project/alsa-devel/patch/20200325103322.2508-4-tiwai@suse.de/

Please, attach the `strace` output then.

2022-07-28 11:07 UTC, christophehenry commented on ucm2/USB-Audio/Rane/SL-1-HiFi.conf
> +		CapturePCM "hw:${CardId},4"
[Here it is](https://gist.github.com/christophehenry/9933c8876a34868ea47e52a9069013d0).

2022-07-28 14:08 UTC, perexg commented on ucm2/USB-Audio/Rane/SL-1-HiFi.conf
> +		CapturePCM "hw:${CardId},4"
```
openat(AT_FDCWD, "/dev/snd/controlC2", O_RDWR|O_CLOEXEC) = 3
ioctl(3, SNDRV_CTL_IOCTL_PVERSION, 0x7ffed85023ec) = 0
ioctl(3, SNDRV_CTL_IOCTL_PCM_PREFER_SUBDEVICE, 0x7ffed850244c) = 0
openat(AT_FDCWD, "/dev/snd/pcmC2D0c", O_RDWR|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (Aucun fichier ou dossier de ce type)
```

```
ARECORD

**** List of CAPTURE Hardware Devices ****
card 1: Generic [HD-Audio Generic], device 0: ALC293 Analog [ALC293 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: SL1 [SL-1], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: SL1 [SL-1], device 1: USB Audio [USB Audio #1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: SL1 [SL-1], device 2: USB Audio [USB Audio #2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

It looks like a driver (or udev??) issue - the devices are listed, but they are not accessible. @tiwai - FYI.

2022-08-14 20:46 UTC, F1iX commented
I am dealing with the exact same problem: Mixxx on Arch Linux only detects the outputs and one input (I confirmed it is the 6.5mm microphone jack) - the two vinyl inputs are missing. Did the changes in your latest push fix the issue? How can I apply the changes to my system?

2022-08-15 10:49 UTC, christophehenry commented
No, this seems to be a kernel bug. [The original ticket was reopened](https://bugzilla.kernel.org/show_bug.cgi?id=216082#c14). This PR can only be merged once the kernel bug is resolved.

2022-09-13 17:02 UTC, christophehenry commented
Now that [ALSA#216082](https://bugzilla.kernel.org/show_bug.cgi?id=216082) is to be solved in kernel 6.0, I think it's time to move this forward.

![](https://user-images.githubusercontent.com/22097904/189962601-82e46542-366f-469c-8e63-8d1f54a40cf7.png)

FYI, `echo 'options snd-usb-audio delayed_register=13e50001:07' > /etc/modprobe.d/rane.conf` solves the bug for kernel < 6.0

2022-09-16 08:25 UTC, perexg requested changes

2022-09-16 08:25 UTC, perexg commented on ucm2/USB-Audio/Rane/SL-1-HiFi.conf
> +		PlaybackChannels 2
2 channels are the default. This line is extra.

2022-09-16 18:11 UTC, closed without merging