Tegra: add
alsa-project/alsa-ucm-conf pull request #291
Opened 2023-03-14 07:54 UTC by clamor-s

2023-03-20 14:37 UTC, perexg requested changes
Quick comments:

- lack of hardware volume control
- most of default settings should go to BootSequence so users can alter them using standard mixer tools
- the common verb initialization should be in SectionDefaults - see https://www.alsa-project.org/alsa-doc/alsa-lib/group__ucm__conf.html

2023-03-20 15:18 UTC, clamor-s commented
> * lack of hardware volume control
All 3 have hw volume control for output, rt5631 and wm8903 have no hw volume control for input in codec and max98089 in case of lg has 2 independent controls for both mics so I decided not to expose them separately.

> * most of default settings should go to BootSequence so users can alter them using standard mixer tools
All 3 have common boot sections and device sections include only stuff which is changed for device to work

> * the common verb initialization should be in SectionDefaults
Specify which ucm you are referring to

2023-03-20 18:37 UTC, perexg commented
> > * lack of hardware volume control
> 
> All 3 have hw volume control for output, rt5631 and wm8903 have no hw volume control for input in codec and max98089 in case of lg has 2 independent controls for both mics so I decided not to expose them separately.

I don't see PlaybackMixerElem nor CaptureMixerElem values. Which audio server did you use for the hw volume control tests? PA or PW use only Elem mixer controls. The goal is that the sound server changes the hardware volume controls when you slide / set the volume level through the audio server's API.

Also, if you set fixed values in the verb's EnableSequence, then the hardware volume control cannot work. The presets should be in the BootSequence which you do not use at all. It seems like an old configuration scheme.

> > * most of default settings should go to BootSequence so users can alter them using standard mixer tools
> 
> All 3 have common boot sections and device sections include only stuff which is changed for device to work

I see only verb sections.

> > * the common verb initialization should be in SectionDefaults
> 
> Specify which ucm you are referring to

x3 / HiFi / VoiceCall for example, the EnableSequence (s) are almost similar

2023-03-21 09:45 UTC, clamor-s commented
> > > * lack of hardware volume control
> > 
> > 
> > All 3 have hw volume control for output, rt5631 and wm8903 have no hw volume control for input in codec and max98089 in case of lg has 2 independent controls for both mics so I decided not to expose them separately.
> 
> I don't see PlaybackMixerElem nor CaptureMixerElem values. Which audio server did you use for the hw volume control tests? PA or PW use only Elem mixer controls. The goal is that the sound server changes the hardware volume controls when you slide / set the volume level through the audio server's API.
> 
> Also, if you set fixed values in the verb's EnableSequence, then the hardware volume control cannot work. The presets should be in the BootSequence which you do not use at all. It seems like an old configuration scheme.
> 

`PlaybackMixerElem` is implemented and tested on all 3. `CaptureMixerElem`, `CaptureVolume` and `CaptureSwitch` do not work at all.

> > > * most of default settings should go to BootSequence so users can alter them using standard mixer tools
> > 
> > 
> > All 3 have common boot sections and device sections include only stuff which is changed for device to work
> 
> I see only verb sections.
> 

`EnableSequence` of first section moved as `BootSequence`.

> > > * the common verb initialization should be in SectionDefaults
> > 
> > 
> > Specify which ucm you are referring to
> 
> x3 / HiFi / VoiceCall for example, the EnableSequence (s) are almost similar

`EnableSequence` of first section hifi and call moved as `BootSequence`.

P. S. Switching HiFi to Call configs and backwards on max98089 brakes HW connections of ALSA and PA. I need to reload configs to fix that.

2023-03-21 10:01 UTC, clamor-s commented
> Please, fix that. You can dump the mixer state using `amixer contents` and compare the working/non-working state. If something is different, check your verb's enable / disable sequences. Again, the section execution diagram is in the documentation - https://www.alsa-project.org/alsa-doc/alsa-lib/group__ucm__conf.html .

This is not my issue, this is global issue. I have tested all my devices (switched HiFi to Off and back) and all got this disruption.

2023-04-17 10:34 UTC, perexg commented
Show / analyze debug output from pulseaudio or you may try `spa-acp-tool` from pipewire to analyze the volume setting issue.

2023-08-01 17:03 UTC, clamor-s commented
@perexg hello?

2023-08-01 18:13 UTC, perexg commented
Correct SectionDevice names - use only names from https://github.com/alsa-project/alsa-lib/blob/master/include/use-case.h#L132-L145 .

2023-08-04 11:23 UTC, clamor-s commented
> Correct SectionDevice names - use only names from https://github.com/alsa-project/alsa-lib/blob/master/include/use-case.h#L132-L145 .

applied and tested

2023-08-05 19:44 UTC, clamor-s commented
@perexg ^

2023-08-14 07:06 UTC, clamor-s commented
@perexg any other improvements required?

2023-08-21 13:34 UTC, closed without merging